# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Myhäilyjä / Musings
email: janne.j.peltola@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Janne Peltolan blogi ja erinäisten sisältöjen loppusijoituspaikka.
  A dumping site for my thoughts and miscellaneous blog-like content.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jannepeltola.github.io" # the base hostname & protocol for your site
twitter_username: JannePeltola
github_username:  jannepeltola
linkedin_username: jannepeltola

# Build settings
markdown: kramdown
